{{- if gt (int .Values.replicaCount) 1 }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rauthy.fullname" . }}-hiqlite-headless
  labels:
    {{- include "rauthy.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  sessionAffinity: None
  selector:
    {{- include "rauthy.selectorLabels" . | nindent 4 }}
  ports:
    - name: hiqlite-raft
      protocol: TCP
      port: {{ .Values.hiqlite.ports.raft }}
      targetPort: hiqlite-raft
    - name: hiqlite-api
      protocol: TCP
      port: {{ .Values.hiqlite.ports.api }}
      targetPort: hiqlite-api
{{- end }}