{{- if gt (int .Values.replicaCount) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "rauthy-helm.fullname" . }}
  labels:
    {{- include "rauthy-helm.labels" . | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "rauthy-helm.selectorLabels" . | nindent 6 }}
{{- end }}